[package]
name = "kernel"
version = "0.1.0"
edition = "2018"

[dependencies]
seq-macro = "0.2.1"

[build-dependencies]
cc = "1.0"

[profile.dev]
panic = "abort"
opt-level = 3
lto = true

[profile.release]
panic = "abort"
opt-level = 3
lto = true